FROM nginx:alpine

# Copy static files into the default nginx html directory
COPY index.html /usr/share/nginx/html/
COPY htmls/ /usr/share/nginx/html/htmls/
COPY styles.css /usr/share/nginx/html/
COPY srcs/ /usr/share/nginx/html/srcs/
COPY Database/ /usr/share/nginx/html/Database/


# Optional: use a custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80